version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./
    image: mini-agent-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      CORS_ORIGINS: http://localhost:3000
    command: bash backend/run.sh
    ports:
      - "8000:8000"
volumes:
  pgdata:

